sudo: false

apt:
  packages:
  - libgflags-dev
  - libgtest-dev

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install --upgrade tox
  - pip install --upgrade protobuf
  - pip install coveralls
  - pip install -U -r backend_server/requirements/setup/requirements_dev.txt

script:
  - PYTHONPATH=backend_server:$PYTHONPATH py.test -vs backend_server/tests

after_success:
  - coveralls
